---
#Command Execution
- name: Show Ip Arp Entries
  hosts: Sandbox
  gather_facts: false
  connection: local
  tasks:
   - name: Show IP Arp and Output to command line
     ios_command:
      commands: 'show ip arp'
     register: output
#Output to CLI
   - debug:
       var: output.stdout_lines
#End of Code
